# Generated by Django 4.2.6 on 2023-12-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='Highest_value',
        ),
        migrations.AlterField(
            model_name='result_tbl',
            name='Highest_value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
